export const Footer = ({ invoice }) => (
  <div className="mt-8 text-center text-gray-600">
    {invoice.user.companyStamp && invoice.user.companyAuthorizedSign ? (
      <div className="flex justify-between items-center mb-4">
        <div>
          <img src={invoice.user.companyStamp} alt="Company Stamp" className="w-32 h-16 object-contain mb-2" />
          <p className="text-xs">Company Stamp</p>
        </div>
        <div>
          <img src={invoice.user.companyAuthorizedSign} alt="Authorized Signature" className="w-32 h-16 object-contain mb-2" />
          <p className="text-xs">Authorized Signature</p>
        </div>
      </div>
    ) : (
      <p className="text-sm mb-4">This is a digitally generated invoice and does not require a physical signature.</p>
    )}
    <div className="mt-8 text-center text-xs text-gray-500">
      <p>Thank you for your business!</p>
      <p className="mt-1">
        © {new Date().getFullYear()} Invoice Pro SaaS. This invoice is generated by Invoice Pro Saas Developed by software engineers.
      </p>
    </div>
  </div>
);
